"""create db

Revision ID: 46df8acc101
Revises: 
Create Date: 2015-10-05 14:40:47.522839

"""

# revision identifiers, used by Alembic.
revision = '46df8acc101'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_confs',
    sa.Column('source_type', sa.String(convert_unicode=True), nullable=False),
    sa.Column('stream_name', sa.String(convert_unicode=True), nullable=False),
    sa.Column('url', sa.String(convert_unicode=True), nullable=False),
    sa.Column('api_tcp_port', sa.Integer(), server_default='0', nullable=False),
    sa.Column('log_file', sa.String(convert_unicode=True), nullable=True),
    sa.Column('log_size', sa.Integer(), server_default='1048576', nullable=False),
    sa.Column('log_rotate', sa.Integer(), server_default='3', nullable=False),
    sa.Column('err_restart_interval', sa.Float(), server_default='30.0', nullable=False),
    sa.Column('age_time', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('extra_options_json', sa.Text(convert_unicode=True), nullable=False),
    sa.Column('other_kwargs_json', sa.Text(convert_unicode=True), nullable=False),
    sa.PrimaryKeyConstraint('stream_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_confs')
    ### end Alembic commands ###
