# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_client_list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_client_heartbeat_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_client_list.proto',
  package='stream_switch',
  serialized_pb=_b('\n\x14pb_client_list.proto\x12\rstream_switch\x1a\x19pb_client_heartbeat.proto\"=\n\x12ProtoClientListReq\x12\x13\n\x0bstart_index\x18\x01 \x01(\r\x12\x12\n\nclient_num\x18\x02 \x01(\r\"y\n\x12ProtoClientListRep\x12\x11\n\ttotal_num\x18\x01 \x01(\r\x12\x13\n\x0bstart_index\x18\x02 \x01(\r\x12;\n\x0b\x63lient_list\x18@ \x03(\x0b\x32&.stream_switch.ProtoClientHeartbeatReq')
  ,
  dependencies=[pb_client_heartbeat_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOCLIENTLISTREQ = _descriptor.Descriptor(
  name='ProtoClientListReq',
  full_name='stream_switch.ProtoClientListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_index', full_name='stream_switch.ProtoClientListReq.start_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_num', full_name='stream_switch.ProtoClientListReq.client_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=127,
)


_PROTOCLIENTLISTREP = _descriptor.Descriptor(
  name='ProtoClientListRep',
  full_name='stream_switch.ProtoClientListRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_num', full_name='stream_switch.ProtoClientListRep.total_num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_index', full_name='stream_switch.ProtoClientListRep.start_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_list', full_name='stream_switch.ProtoClientListRep.client_list', index=2,
      number=64, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=250,
)

_PROTOCLIENTLISTREP.fields_by_name['client_list'].message_type = pb_client_heartbeat_pb2._PROTOCLIENTHEARTBEATREQ
DESCRIPTOR.message_types_by_name['ProtoClientListReq'] = _PROTOCLIENTLISTREQ
DESCRIPTOR.message_types_by_name['ProtoClientListRep'] = _PROTOCLIENTLISTREP

ProtoClientListReq = _reflection.GeneratedProtocolMessageType('ProtoClientListReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCLIENTLISTREQ,
  __module__ = 'pb_client_list_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoClientListReq)
  ))
_sym_db.RegisterMessage(ProtoClientListReq)

ProtoClientListRep = _reflection.GeneratedProtocolMessageType('ProtoClientListRep', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCLIENTLISTREP,
  __module__ = 'pb_client_list_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoClientListRep)
  ))
_sym_db.RegisterMessage(ProtoClientListRep)


# @@protoc_insertion_point(module_scope)
