# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_client_heartbeat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_client_heartbeat.proto',
  package='stream_switch',
  serialized_pb=_b('\n\x19pb_client_heartbeat.proto\x12\rstream_switch\"\xdf\x01\n\x17ProtoClientHeartbeatReq\x12>\n\x11\x63lient_ip_version\x18\x01 \x01(\x0e\x32#.stream_switch.ProtoClientIPVersion\x12\x11\n\tclient_ip\x18\x02 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x03 \x01(\x05\x12\x14\n\x0c\x63lient_token\x18\x04 \x01(\t\x12\x17\n\x0f\x63lient_protocol\x18\x05 \x01(\t\x12\x13\n\x0b\x63lient_text\x18\x06 \x01(\t\x12\x18\n\x10last_active_time\x18\x07 \x01(\x03\";\n\x17ProtoClientHeartbeatRep\x12\r\n\x05lease\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03*H\n\x14ProtoClientIPVersion\x12\x17\n\x13PROTO_IP_VERSION_V4\x10\x00\x12\x17\n\x13PROTO_IP_VERSION_V6\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOCLIENTIPVERSION = _descriptor.EnumDescriptor(
  name='ProtoClientIPVersion',
  full_name='stream_switch.ProtoClientIPVersion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_IP_VERSION_V4', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_IP_VERSION_V6', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=331,
  serialized_end=403,
)
_sym_db.RegisterEnumDescriptor(_PROTOCLIENTIPVERSION)

ProtoClientIPVersion = enum_type_wrapper.EnumTypeWrapper(_PROTOCLIENTIPVERSION)
PROTO_IP_VERSION_V4 = 0
PROTO_IP_VERSION_V6 = 1



_PROTOCLIENTHEARTBEATREQ = _descriptor.Descriptor(
  name='ProtoClientHeartbeatReq',
  full_name='stream_switch.ProtoClientHeartbeatReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_ip_version', full_name='stream_switch.ProtoClientHeartbeatReq.client_ip_version', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='stream_switch.ProtoClientHeartbeatReq.client_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_port', full_name='stream_switch.ProtoClientHeartbeatReq.client_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_token', full_name='stream_switch.ProtoClientHeartbeatReq.client_token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_protocol', full_name='stream_switch.ProtoClientHeartbeatReq.client_protocol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_text', full_name='stream_switch.ProtoClientHeartbeatReq.client_text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_active_time', full_name='stream_switch.ProtoClientHeartbeatReq.last_active_time', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=268,
)


_PROTOCLIENTHEARTBEATREP = _descriptor.Descriptor(
  name='ProtoClientHeartbeatRep',
  full_name='stream_switch.ProtoClientHeartbeatRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lease', full_name='stream_switch.ProtoClientHeartbeatRep.lease', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='stream_switch.ProtoClientHeartbeatRep.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=329,
)

_PROTOCLIENTHEARTBEATREQ.fields_by_name['client_ip_version'].enum_type = _PROTOCLIENTIPVERSION
DESCRIPTOR.message_types_by_name['ProtoClientHeartbeatReq'] = _PROTOCLIENTHEARTBEATREQ
DESCRIPTOR.message_types_by_name['ProtoClientHeartbeatRep'] = _PROTOCLIENTHEARTBEATREP
DESCRIPTOR.enum_types_by_name['ProtoClientIPVersion'] = _PROTOCLIENTIPVERSION

ProtoClientHeartbeatReq = _reflection.GeneratedProtocolMessageType('ProtoClientHeartbeatReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCLIENTHEARTBEATREQ,
  __module__ = 'pb_client_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoClientHeartbeatReq)
  ))
_sym_db.RegisterMessage(ProtoClientHeartbeatReq)

ProtoClientHeartbeatRep = _reflection.GeneratedProtocolMessageType('ProtoClientHeartbeatRep', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCLIENTHEARTBEATREP,
  __module__ = 'pb_client_heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoClientHeartbeatRep)
  ))
_sym_db.RegisterMessage(ProtoClientHeartbeatRep)


# @@protoc_insertion_point(module_scope)
