# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_media.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_media.proto',
  package='stream_switch',
  serialized_pb=_b('\n\x0epb_media.proto\x12\rstream_switch\"\x14\n\x12ProtoMediaFrameReq\"\xa6\x01\n\x12ProtoMediaFrameMsg\x12\x14\n\x0cstream_index\x18\x01 \x01(\x05\x12\x0b\n\x03sec\x18\x02 \x01(\x03\x12\x0c\n\x04usec\x18\x03 \x01(\x05\x12\x36\n\nframe_type\x18\x04 \x01(\x0e\x32\".stream_switch.ProtoMediaFrameType\x12\x0c\n\x04ssrc\x18\x05 \x01(\r\x12\x0b\n\x03seq\x18\x06 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18@ \x01(\x0c*\x9d\x01\n\x13ProtoMediaFrameType\x12\x1f\n\x1bPROTO_MEDIA_FRAME_KEY_FRAME\x10\x00\x12 \n\x1cPROTO_MEDIA_FRAME_DATA_FRAME\x10\x01\x12!\n\x1dPROTO_MEDIA_FRAME_PARAM_FRAME\x10\x02\x12 \n\x1bPROTO_MEDIA_FRAME_EOF_FRAME\x10\x80\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOMEDIAFRAMETYPE = _descriptor.EnumDescriptor(
  name='ProtoMediaFrameType',
  full_name='stream_switch.ProtoMediaFrameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_MEDIA_FRAME_KEY_FRAME', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_MEDIA_FRAME_DATA_FRAME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_MEDIA_FRAME_PARAM_FRAME', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_MEDIA_FRAME_EOF_FRAME', index=3, number=256,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=225,
  serialized_end=382,
)
_sym_db.RegisterEnumDescriptor(_PROTOMEDIAFRAMETYPE)

ProtoMediaFrameType = enum_type_wrapper.EnumTypeWrapper(_PROTOMEDIAFRAMETYPE)
PROTO_MEDIA_FRAME_KEY_FRAME = 0
PROTO_MEDIA_FRAME_DATA_FRAME = 1
PROTO_MEDIA_FRAME_PARAM_FRAME = 2
PROTO_MEDIA_FRAME_EOF_FRAME = 256



_PROTOMEDIAFRAMEREQ = _descriptor.Descriptor(
  name='ProtoMediaFrameReq',
  full_name='stream_switch.ProtoMediaFrameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=53,
)


_PROTOMEDIAFRAMEMSG = _descriptor.Descriptor(
  name='ProtoMediaFrameMsg',
  full_name='stream_switch.ProtoMediaFrameMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_index', full_name='stream_switch.ProtoMediaFrameMsg.stream_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sec', full_name='stream_switch.ProtoMediaFrameMsg.sec', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usec', full_name='stream_switch.ProtoMediaFrameMsg.usec', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_type', full_name='stream_switch.ProtoMediaFrameMsg.frame_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssrc', full_name='stream_switch.ProtoMediaFrameMsg.ssrc', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stream_switch.ProtoMediaFrameMsg.seq', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='stream_switch.ProtoMediaFrameMsg.data', index=6,
      number=64, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=222,
)

_PROTOMEDIAFRAMEMSG.fields_by_name['frame_type'].enum_type = _PROTOMEDIAFRAMETYPE
DESCRIPTOR.message_types_by_name['ProtoMediaFrameReq'] = _PROTOMEDIAFRAMEREQ
DESCRIPTOR.message_types_by_name['ProtoMediaFrameMsg'] = _PROTOMEDIAFRAMEMSG
DESCRIPTOR.enum_types_by_name['ProtoMediaFrameType'] = _PROTOMEDIAFRAMETYPE

ProtoMediaFrameReq = _reflection.GeneratedProtocolMessageType('ProtoMediaFrameReq', (_message.Message,), dict(
  DESCRIPTOR = _PROTOMEDIAFRAMEREQ,
  __module__ = 'pb_media_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoMediaFrameReq)
  ))
_sym_db.RegisterMessage(ProtoMediaFrameReq)

ProtoMediaFrameMsg = _reflection.GeneratedProtocolMessageType('ProtoMediaFrameMsg', (_message.Message,), dict(
  DESCRIPTOR = _PROTOMEDIAFRAMEMSG,
  __module__ = 'pb_media_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoMediaFrameMsg)
  ))
_sym_db.RegisterMessage(ProtoMediaFrameMsg)


# @@protoc_insertion_point(module_scope)
