# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_packet.proto',
  package='stream_switch',
  serialized_pb=_b('\n\x0fpb_packet.proto\x12\rstream_switch\"\xb4\x01\n\x11ProtoCommonHeader\x12\x12\n\x07version\x18\x01 \x01(\r:\x01\x31\x12G\n\x04type\x18\x02 \x01(\x0e\x32\x1e.stream_switch.ProtoPacketType:\x19PROTO_PACKET_TYPE_REQUEST\x12\x0f\n\x04\x63ode\x18\x03 \x01(\x05:\x01\x30\x12\x0e\n\x03seq\x18\x04 \x01(\r:\x01\x30\x12\x13\n\x06status\x18\x05 \x01(\x05:\x03\x32\x30\x30\x12\x0c\n\x04info\x18\x06 \x01(\t\"S\n\x11ProtoCommonPacket\x12\x30\n\x06header\x18\x01 \x01(\x0b\x32 .stream_switch.ProtoCommonHeader\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c*l\n\x0fProtoPacketType\x12\x1d\n\x19PROTO_PACKET_TYPE_REQUEST\x10\x00\x12\x1b\n\x17PROTO_PACKET_TYPE_REPLY\x10\x01\x12\x1d\n\x19PROTO_PACKET_TYPE_MESSAGE\x10\x02*\xa1\x01\n\x11ProtoPacketStatus\x12\x1b\n\x16PROTO_PACKET_STATUS_OK\x10\xc8\x01\x12$\n\x1fPROTO_PACKET_STATUS_BAD_REQUEST\x10\x90\x03\x12\"\n\x1dPROTO_PACKET_STATUS_NOT_FOUND\x10\x94\x03\x12%\n PROTO_PACKET_STATUS_INTERNAL_ERR\x10\xf4\x03*\xa3\x02\n\x0fProtoPacketCode\x12\x1d\n\x19PROTO_PACKET_CODE_INVALID\x10\x00\x12\x1e\n\x1aPROTO_PACKET_CODE_METADATA\x10\x01\x12\x1b\n\x17PROTO_PACKET_CODE_MEDIA\x10\x02\x12!\n\x1dPROTO_PACKET_CODE_STREAM_INFO\x10\x03\x12\x1f\n\x1bPROTO_PACKET_CODE_KEY_FRAME\x10\x04\x12&\n\"PROTO_PACKET_CODE_CLIENT_HEARTBEAT\x10\x05\x12%\n!PROTO_PACKET_CODE_MEDIA_STATISTIC\x10\x06\x12!\n\x1dPROTO_PACKET_CODE_CLIENT_LIST\x10\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOPACKETTYPE = _descriptor.EnumDescriptor(
  name='ProtoPacketType',
  full_name='stream_switch.ProtoPacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_TYPE_REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_TYPE_REPLY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_TYPE_MESSAGE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=302,
  serialized_end=410,
)
_sym_db.RegisterEnumDescriptor(_PROTOPACKETTYPE)

ProtoPacketType = enum_type_wrapper.EnumTypeWrapper(_PROTOPACKETTYPE)
_PROTOPACKETSTATUS = _descriptor.EnumDescriptor(
  name='ProtoPacketStatus',
  full_name='stream_switch.ProtoPacketStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_STATUS_OK', index=0, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_STATUS_BAD_REQUEST', index=1, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_STATUS_NOT_FOUND', index=2, number=404,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_STATUS_INTERNAL_ERR', index=3, number=500,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=413,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_PROTOPACKETSTATUS)

ProtoPacketStatus = enum_type_wrapper.EnumTypeWrapper(_PROTOPACKETSTATUS)
_PROTOPACKETCODE = _descriptor.EnumDescriptor(
  name='ProtoPacketCode',
  full_name='stream_switch.ProtoPacketCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_INVALID', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_METADATA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_MEDIA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_STREAM_INFO', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_KEY_FRAME', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_CLIENT_HEARTBEAT', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_MEDIA_STATISTIC', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_PACKET_CODE_CLIENT_LIST', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=577,
  serialized_end=868,
)
_sym_db.RegisterEnumDescriptor(_PROTOPACKETCODE)

ProtoPacketCode = enum_type_wrapper.EnumTypeWrapper(_PROTOPACKETCODE)
PROTO_PACKET_TYPE_REQUEST = 0
PROTO_PACKET_TYPE_REPLY = 1
PROTO_PACKET_TYPE_MESSAGE = 2
PROTO_PACKET_STATUS_OK = 200
PROTO_PACKET_STATUS_BAD_REQUEST = 400
PROTO_PACKET_STATUS_NOT_FOUND = 404
PROTO_PACKET_STATUS_INTERNAL_ERR = 500
PROTO_PACKET_CODE_INVALID = 0
PROTO_PACKET_CODE_METADATA = 1
PROTO_PACKET_CODE_MEDIA = 2
PROTO_PACKET_CODE_STREAM_INFO = 3
PROTO_PACKET_CODE_KEY_FRAME = 4
PROTO_PACKET_CODE_CLIENT_HEARTBEAT = 5
PROTO_PACKET_CODE_MEDIA_STATISTIC = 6
PROTO_PACKET_CODE_CLIENT_LIST = 7



_PROTOCOMMONHEADER = _descriptor.Descriptor(
  name='ProtoCommonHeader',
  full_name='stream_switch.ProtoCommonHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='stream_switch.ProtoCommonHeader.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='stream_switch.ProtoCommonHeader.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='stream_switch.ProtoCommonHeader.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='stream_switch.ProtoCommonHeader.seq', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='stream_switch.ProtoCommonHeader.status', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=200,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='stream_switch.ProtoCommonHeader.info', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=215,
)


_PROTOCOMMONPACKET = _descriptor.Descriptor(
  name='ProtoCommonPacket',
  full_name='stream_switch.ProtoCommonPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='stream_switch.ProtoCommonPacket.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='stream_switch.ProtoCommonPacket.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=300,
)

_PROTOCOMMONHEADER.fields_by_name['type'].enum_type = _PROTOPACKETTYPE
_PROTOCOMMONPACKET.fields_by_name['header'].message_type = _PROTOCOMMONHEADER
DESCRIPTOR.message_types_by_name['ProtoCommonHeader'] = _PROTOCOMMONHEADER
DESCRIPTOR.message_types_by_name['ProtoCommonPacket'] = _PROTOCOMMONPACKET
DESCRIPTOR.enum_types_by_name['ProtoPacketType'] = _PROTOPACKETTYPE
DESCRIPTOR.enum_types_by_name['ProtoPacketStatus'] = _PROTOPACKETSTATUS
DESCRIPTOR.enum_types_by_name['ProtoPacketCode'] = _PROTOPACKETCODE

ProtoCommonHeader = _reflection.GeneratedProtocolMessageType('ProtoCommonHeader', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOMMONHEADER,
  __module__ = 'pb_packet_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoCommonHeader)
  ))
_sym_db.RegisterMessage(ProtoCommonHeader)

ProtoCommonPacket = _reflection.GeneratedProtocolMessageType('ProtoCommonPacket', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOMMONPACKET,
  __module__ = 'pb_packet_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoCommonPacket)
  ))
_sym_db.RegisterMessage(ProtoCommonPacket)


# @@protoc_insertion_point(module_scope)
