# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_stream_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_metadata_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_stream_info.proto',
  package='stream_switch',
  serialized_pb=_b('\n\x14pb_stream_info.proto\x12\rstream_switch\x1a\x11pb_metadata.proto\"\x9d\x02\n\x12ProtoStreamInfoMsg\x12\x34\n\x05state\x18\x01 \x01(\x0e\x32%.stream_switch.ProtoSourceStreamState\x12/\n\tplay_type\x18\x02 \x01(\x0e\x32\x1c.stream_switch.ProtoPlayType\x12\x14\n\x0csource_proto\x18\x03 \x01(\t\x12\x0c\n\x04ssrc\x18\x04 \x01(\r\x12\x0f\n\x07\x63ur_bps\x18\x05 \x01(\r\x12\x16\n\x0elast_frame_sec\x18\x06 \x01(\x03\x12\x17\n\x0flast_frame_usec\x18\x07 \x01(\x05\x12\x11\n\tsend_time\x18\x08 \x01(\x03\x12\x13\n\x0bstream_name\x18\t \x01(\t\x12\x12\n\nclient_num\x18\n \x01(\x05*\xe5\x02\n\x16ProtoSourceStreamState\x12(\n$PROTO_SOURCE_STREAM_STATE_CONNECTING\x10\x00\x12 \n\x1cPROTO_SOURCE_STREAM_STATE_OK\x10\x01\x12*\n\x1dPROTO_SOURCE_STREAM_STATE_ERR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x37\n*PROTO_SOURCE_STREAM_STATE_ERR_CONNECT_FAIL\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x35\n(PROTO_SOURCE_STREAM_STATE_ERR_MEIDA_STOP\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12/\n\"PROTO_SOURCE_STREAM_STATE_ERR_TIME\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x32\n%PROTO_SOURCE_STREAM_STATE_ERR_TIMEOUT\x10\x81\xfe\xff\xff\xff\xff\xff\xff\xff\x01')
  ,
  dependencies=[pb_metadata_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOSOURCESTREAMSTATE = _descriptor.EnumDescriptor(
  name='ProtoSourceStreamState',
  full_name='stream_switch.ProtoSourceStreamState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_CONNECTING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_ERR', index=2, number=-1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_ERR_CONNECT_FAIL', index=3, number=-2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_ERR_MEIDA_STOP', index=4, number=-3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_ERR_TIME', index=5, number=-4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTO_SOURCE_STREAM_STATE_ERR_TIMEOUT', index=6, number=-255,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=347,
  serialized_end=704,
)
_sym_db.RegisterEnumDescriptor(_PROTOSOURCESTREAMSTATE)

ProtoSourceStreamState = enum_type_wrapper.EnumTypeWrapper(_PROTOSOURCESTREAMSTATE)
PROTO_SOURCE_STREAM_STATE_CONNECTING = 0
PROTO_SOURCE_STREAM_STATE_OK = 1
PROTO_SOURCE_STREAM_STATE_ERR = -1
PROTO_SOURCE_STREAM_STATE_ERR_CONNECT_FAIL = -2
PROTO_SOURCE_STREAM_STATE_ERR_MEIDA_STOP = -3
PROTO_SOURCE_STREAM_STATE_ERR_TIME = -4
PROTO_SOURCE_STREAM_STATE_ERR_TIMEOUT = -255



_PROTOSTREAMINFOMSG = _descriptor.Descriptor(
  name='ProtoStreamInfoMsg',
  full_name='stream_switch.ProtoStreamInfoMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='stream_switch.ProtoStreamInfoMsg.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='play_type', full_name='stream_switch.ProtoStreamInfoMsg.play_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_proto', full_name='stream_switch.ProtoStreamInfoMsg.source_proto', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssrc', full_name='stream_switch.ProtoStreamInfoMsg.ssrc', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cur_bps', full_name='stream_switch.ProtoStreamInfoMsg.cur_bps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_frame_sec', full_name='stream_switch.ProtoStreamInfoMsg.last_frame_sec', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_frame_usec', full_name='stream_switch.ProtoStreamInfoMsg.last_frame_usec', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send_time', full_name='stream_switch.ProtoStreamInfoMsg.send_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='stream_switch.ProtoStreamInfoMsg.stream_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_num', full_name='stream_switch.ProtoStreamInfoMsg.client_num', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=344,
)

_PROTOSTREAMINFOMSG.fields_by_name['state'].enum_type = _PROTOSOURCESTREAMSTATE
_PROTOSTREAMINFOMSG.fields_by_name['play_type'].enum_type = pb_metadata_pb2._PROTOPLAYTYPE
DESCRIPTOR.message_types_by_name['ProtoStreamInfoMsg'] = _PROTOSTREAMINFOMSG
DESCRIPTOR.enum_types_by_name['ProtoSourceStreamState'] = _PROTOSOURCESTREAMSTATE

ProtoStreamInfoMsg = _reflection.GeneratedProtocolMessageType('ProtoStreamInfoMsg', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTREAMINFOMSG,
  __module__ = 'pb_stream_info_pb2'
  # @@protoc_insertion_point(class_scope:stream_switch.ProtoStreamInfoMsg)
  ))
_sym_db.RegisterMessage(ProtoStreamInfoMsg)


# @@protoc_insertion_point(module_scope)
