// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_client_list.proto

#ifndef PROTOBUF_pb_5fclient_5flist_2eproto__INCLUDED
#define PROTOBUF_pb_5fclient_5flist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "pb_client_heartbeat.pb.h"
// @@protoc_insertion_point(includes)

namespace stream_switch {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pb_5fclient_5flist_2eproto();
void protobuf_AssignDesc_pb_5fclient_5flist_2eproto();
void protobuf_ShutdownFile_pb_5fclient_5flist_2eproto();

class ProtoClientListReq;
class ProtoClientListRep;

// ===================================================================

class ProtoClientListReq : public ::google::protobuf::Message {
 public:
  ProtoClientListReq();
  virtual ~ProtoClientListReq();

  ProtoClientListReq(const ProtoClientListReq& from);

  inline ProtoClientListReq& operator=(const ProtoClientListReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoClientListReq& default_instance();

  void Swap(ProtoClientListReq* other);

  // implements Message ----------------------------------------------

  ProtoClientListReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoClientListReq& from);
  void MergeFrom(const ProtoClientListReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 start_index = 1;
  inline bool has_start_index() const;
  inline void clear_start_index();
  static const int kStartIndexFieldNumber = 1;
  inline ::google::protobuf::uint32 start_index() const;
  inline void set_start_index(::google::protobuf::uint32 value);

  // optional uint32 client_num = 2;
  inline bool has_client_num() const;
  inline void clear_client_num();
  static const int kClientNumFieldNumber = 2;
  inline ::google::protobuf::uint32 client_num() const;
  inline void set_client_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:stream_switch.ProtoClientListReq)
 private:
  inline void set_has_start_index();
  inline void clear_has_start_index();
  inline void set_has_client_num();
  inline void clear_has_client_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 start_index_;
  ::google::protobuf::uint32 client_num_;
  friend void  protobuf_AddDesc_pb_5fclient_5flist_2eproto();
  friend void protobuf_AssignDesc_pb_5fclient_5flist_2eproto();
  friend void protobuf_ShutdownFile_pb_5fclient_5flist_2eproto();

  void InitAsDefaultInstance();
  static ProtoClientListReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoClientListRep : public ::google::protobuf::Message {
 public:
  ProtoClientListRep();
  virtual ~ProtoClientListRep();

  ProtoClientListRep(const ProtoClientListRep& from);

  inline ProtoClientListRep& operator=(const ProtoClientListRep& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoClientListRep& default_instance();

  void Swap(ProtoClientListRep* other);

  // implements Message ----------------------------------------------

  ProtoClientListRep* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoClientListRep& from);
  void MergeFrom(const ProtoClientListRep& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 total_num = 1;
  inline bool has_total_num() const;
  inline void clear_total_num();
  static const int kTotalNumFieldNumber = 1;
  inline ::google::protobuf::uint32 total_num() const;
  inline void set_total_num(::google::protobuf::uint32 value);

  // optional uint32 start_index = 2;
  inline bool has_start_index() const;
  inline void clear_start_index();
  static const int kStartIndexFieldNumber = 2;
  inline ::google::protobuf::uint32 start_index() const;
  inline void set_start_index(::google::protobuf::uint32 value);

  // repeated .stream_switch.ProtoClientHeartbeatReq client_list = 64;
  inline int client_list_size() const;
  inline void clear_client_list();
  static const int kClientListFieldNumber = 64;
  inline const ::stream_switch::ProtoClientHeartbeatReq& client_list(int index) const;
  inline ::stream_switch::ProtoClientHeartbeatReq* mutable_client_list(int index);
  inline ::stream_switch::ProtoClientHeartbeatReq* add_client_list();
  inline const ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoClientHeartbeatReq >&
      client_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoClientHeartbeatReq >*
      mutable_client_list();

  // @@protoc_insertion_point(class_scope:stream_switch.ProtoClientListRep)
 private:
  inline void set_has_total_num();
  inline void clear_has_total_num();
  inline void set_has_start_index();
  inline void clear_has_start_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 total_num_;
  ::google::protobuf::uint32 start_index_;
  ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoClientHeartbeatReq > client_list_;
  friend void  protobuf_AddDesc_pb_5fclient_5flist_2eproto();
  friend void protobuf_AssignDesc_pb_5fclient_5flist_2eproto();
  friend void protobuf_ShutdownFile_pb_5fclient_5flist_2eproto();

  void InitAsDefaultInstance();
  static ProtoClientListRep* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoClientListReq

// optional uint32 start_index = 1;
inline bool ProtoClientListReq::has_start_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoClientListReq::set_has_start_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoClientListReq::clear_has_start_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoClientListReq::clear_start_index() {
  start_index_ = 0u;
  clear_has_start_index();
}
inline ::google::protobuf::uint32 ProtoClientListReq::start_index() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoClientListReq.start_index)
  return start_index_;
}
inline void ProtoClientListReq::set_start_index(::google::protobuf::uint32 value) {
  set_has_start_index();
  start_index_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoClientListReq.start_index)
}

// optional uint32 client_num = 2;
inline bool ProtoClientListReq::has_client_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoClientListReq::set_has_client_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoClientListReq::clear_has_client_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoClientListReq::clear_client_num() {
  client_num_ = 0u;
  clear_has_client_num();
}
inline ::google::protobuf::uint32 ProtoClientListReq::client_num() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoClientListReq.client_num)
  return client_num_;
}
inline void ProtoClientListReq::set_client_num(::google::protobuf::uint32 value) {
  set_has_client_num();
  client_num_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoClientListReq.client_num)
}

// -------------------------------------------------------------------

// ProtoClientListRep

// optional uint32 total_num = 1;
inline bool ProtoClientListRep::has_total_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoClientListRep::set_has_total_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoClientListRep::clear_has_total_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoClientListRep::clear_total_num() {
  total_num_ = 0u;
  clear_has_total_num();
}
inline ::google::protobuf::uint32 ProtoClientListRep::total_num() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoClientListRep.total_num)
  return total_num_;
}
inline void ProtoClientListRep::set_total_num(::google::protobuf::uint32 value) {
  set_has_total_num();
  total_num_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoClientListRep.total_num)
}

// optional uint32 start_index = 2;
inline bool ProtoClientListRep::has_start_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoClientListRep::set_has_start_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoClientListRep::clear_has_start_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoClientListRep::clear_start_index() {
  start_index_ = 0u;
  clear_has_start_index();
}
inline ::google::protobuf::uint32 ProtoClientListRep::start_index() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoClientListRep.start_index)
  return start_index_;
}
inline void ProtoClientListRep::set_start_index(::google::protobuf::uint32 value) {
  set_has_start_index();
  start_index_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoClientListRep.start_index)
}

// repeated .stream_switch.ProtoClientHeartbeatReq client_list = 64;
inline int ProtoClientListRep::client_list_size() const {
  return client_list_.size();
}
inline void ProtoClientListRep::clear_client_list() {
  client_list_.Clear();
}
inline const ::stream_switch::ProtoClientHeartbeatReq& ProtoClientListRep::client_list(int index) const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoClientListRep.client_list)
  return client_list_.Get(index);
}
inline ::stream_switch::ProtoClientHeartbeatReq* ProtoClientListRep::mutable_client_list(int index) {
  // @@protoc_insertion_point(field_mutable:stream_switch.ProtoClientListRep.client_list)
  return client_list_.Mutable(index);
}
inline ::stream_switch::ProtoClientHeartbeatReq* ProtoClientListRep::add_client_list() {
  // @@protoc_insertion_point(field_add:stream_switch.ProtoClientListRep.client_list)
  return client_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoClientHeartbeatReq >&
ProtoClientListRep::client_list() const {
  // @@protoc_insertion_point(field_list:stream_switch.ProtoClientListRep.client_list)
  return client_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoClientHeartbeatReq >*
ProtoClientListRep::mutable_client_list() {
  // @@protoc_insertion_point(field_mutable_list:stream_switch.ProtoClientListRep.client_list)
  return &client_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace stream_switch

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5fclient_5flist_2eproto__INCLUDED
