// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_media_statistic.proto

#ifndef PROTOBUF_pb_5fmedia_5fstatistic_2eproto__INCLUDED
#define PROTOBUF_pb_5fmedia_5fstatistic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "pb_metadata.pb.h"
// @@protoc_insertion_point(includes)

namespace stream_switch {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pb_5fmedia_5fstatistic_2eproto();
void protobuf_AssignDesc_pb_5fmedia_5fstatistic_2eproto();
void protobuf_ShutdownFile_pb_5fmedia_5fstatistic_2eproto();

class ProtoMediaStatisticReq;
class ProtoSubStreamMediaStatistic;
class ProtoMediaStatisticRep;

// ===================================================================

class ProtoMediaStatisticReq : public ::google::protobuf::Message {
 public:
  ProtoMediaStatisticReq();
  virtual ~ProtoMediaStatisticReq();

  ProtoMediaStatisticReq(const ProtoMediaStatisticReq& from);

  inline ProtoMediaStatisticReq& operator=(const ProtoMediaStatisticReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoMediaStatisticReq& default_instance();

  void Swap(ProtoMediaStatisticReq* other);

  // implements Message ----------------------------------------------

  ProtoMediaStatisticReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoMediaStatisticReq& from);
  void MergeFrom(const ProtoMediaStatisticReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:stream_switch.ProtoMediaStatisticReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_AssignDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_ShutdownFile_pb_5fmedia_5fstatistic_2eproto();

  void InitAsDefaultInstance();
  static ProtoMediaStatisticReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoSubStreamMediaStatistic : public ::google::protobuf::Message {
 public:
  ProtoSubStreamMediaStatistic();
  virtual ~ProtoSubStreamMediaStatistic();

  ProtoSubStreamMediaStatistic(const ProtoSubStreamMediaStatistic& from);

  inline ProtoSubStreamMediaStatistic& operator=(const ProtoSubStreamMediaStatistic& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoSubStreamMediaStatistic& default_instance();

  void Swap(ProtoSubStreamMediaStatistic* other);

  // implements Message ----------------------------------------------

  ProtoSubStreamMediaStatistic* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoSubStreamMediaStatistic& from);
  void MergeFrom(const ProtoSubStreamMediaStatistic& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sub_stream_index = 1;
  inline bool has_sub_stream_index() const;
  inline void clear_sub_stream_index();
  static const int kSubStreamIndexFieldNumber = 1;
  inline ::google::protobuf::int32 sub_stream_index() const;
  inline void set_sub_stream_index(::google::protobuf::int32 value);

  // optional .stream_switch.ProtoSubStreamMediaType media_type = 2;
  inline bool has_media_type() const;
  inline void clear_media_type();
  static const int kMediaTypeFieldNumber = 2;
  inline ::stream_switch::ProtoSubStreamMediaType media_type() const;
  inline void set_media_type(::stream_switch::ProtoSubStreamMediaType value);

  // optional uint64 total_bytes = 20;
  inline bool has_total_bytes() const;
  inline void clear_total_bytes();
  static const int kTotalBytesFieldNumber = 20;
  inline ::google::protobuf::uint64 total_bytes() const;
  inline void set_total_bytes(::google::protobuf::uint64 value);

  // optional uint64 key_bytes = 21;
  inline bool has_key_bytes() const;
  inline void clear_key_bytes();
  static const int kKeyBytesFieldNumber = 21;
  inline ::google::protobuf::uint64 key_bytes() const;
  inline void set_key_bytes(::google::protobuf::uint64 value);

  // optional uint64 expected_frames = 30;
  inline bool has_expected_frames() const;
  inline void clear_expected_frames();
  static const int kExpectedFramesFieldNumber = 30;
  inline ::google::protobuf::uint64 expected_frames() const;
  inline void set_expected_frames(::google::protobuf::uint64 value);

  // optional uint64 total_frames = 31;
  inline bool has_total_frames() const;
  inline void clear_total_frames();
  static const int kTotalFramesFieldNumber = 31;
  inline ::google::protobuf::uint64 total_frames() const;
  inline void set_total_frames(::google::protobuf::uint64 value);

  // optional uint64 key_frames = 32;
  inline bool has_key_frames() const;
  inline void clear_key_frames();
  static const int kKeyFramesFieldNumber = 32;
  inline ::google::protobuf::uint64 key_frames() const;
  inline void set_key_frames(::google::protobuf::uint64 value);

  // optional uint64 last_gov = 33;
  inline bool has_last_gov() const;
  inline void clear_last_gov();
  static const int kLastGovFieldNumber = 33;
  inline ::google::protobuf::uint64 last_gov() const;
  inline void set_last_gov(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:stream_switch.ProtoSubStreamMediaStatistic)
 private:
  inline void set_has_sub_stream_index();
  inline void clear_has_sub_stream_index();
  inline void set_has_media_type();
  inline void clear_has_media_type();
  inline void set_has_total_bytes();
  inline void clear_has_total_bytes();
  inline void set_has_key_bytes();
  inline void clear_has_key_bytes();
  inline void set_has_expected_frames();
  inline void clear_has_expected_frames();
  inline void set_has_total_frames();
  inline void clear_has_total_frames();
  inline void set_has_key_frames();
  inline void clear_has_key_frames();
  inline void set_has_last_gov();
  inline void clear_has_last_gov();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 sub_stream_index_;
  int media_type_;
  ::google::protobuf::uint64 total_bytes_;
  ::google::protobuf::uint64 key_bytes_;
  ::google::protobuf::uint64 expected_frames_;
  ::google::protobuf::uint64 total_frames_;
  ::google::protobuf::uint64 key_frames_;
  ::google::protobuf::uint64 last_gov_;
  friend void  protobuf_AddDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_AssignDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_ShutdownFile_pb_5fmedia_5fstatistic_2eproto();

  void InitAsDefaultInstance();
  static ProtoSubStreamMediaStatistic* default_instance_;
};
// -------------------------------------------------------------------

class ProtoMediaStatisticRep : public ::google::protobuf::Message {
 public:
  ProtoMediaStatisticRep();
  virtual ~ProtoMediaStatisticRep();

  ProtoMediaStatisticRep(const ProtoMediaStatisticRep& from);

  inline ProtoMediaStatisticRep& operator=(const ProtoMediaStatisticRep& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoMediaStatisticRep& default_instance();

  void Swap(ProtoMediaStatisticRep* other);

  // implements Message ----------------------------------------------

  ProtoMediaStatisticRep* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoMediaStatisticRep& from);
  void MergeFrom(const ProtoMediaStatisticRep& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ssrc = 1;
  inline bool has_ssrc() const;
  inline void clear_ssrc();
  static const int kSsrcFieldNumber = 1;
  inline ::google::protobuf::uint32 ssrc() const;
  inline void set_ssrc(::google::protobuf::uint32 value);

  // optional int64 timestamp = 2;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  inline ::google::protobuf::int64 timestamp() const;
  inline void set_timestamp(::google::protobuf::int64 value);

  // optional uint64 sum_bytes = 3;
  inline bool has_sum_bytes() const;
  inline void clear_sum_bytes();
  static const int kSumBytesFieldNumber = 3;
  inline ::google::protobuf::uint64 sum_bytes() const;
  inline void set_sum_bytes(::google::protobuf::uint64 value);

  // repeated .stream_switch.ProtoSubStreamMediaStatistic sub_stream_stats = 64;
  inline int sub_stream_stats_size() const;
  inline void clear_sub_stream_stats();
  static const int kSubStreamStatsFieldNumber = 64;
  inline const ::stream_switch::ProtoSubStreamMediaStatistic& sub_stream_stats(int index) const;
  inline ::stream_switch::ProtoSubStreamMediaStatistic* mutable_sub_stream_stats(int index);
  inline ::stream_switch::ProtoSubStreamMediaStatistic* add_sub_stream_stats();
  inline const ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoSubStreamMediaStatistic >&
      sub_stream_stats() const;
  inline ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoSubStreamMediaStatistic >*
      mutable_sub_stream_stats();

  // @@protoc_insertion_point(class_scope:stream_switch.ProtoMediaStatisticRep)
 private:
  inline void set_has_ssrc();
  inline void clear_has_ssrc();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_sum_bytes();
  inline void clear_has_sum_bytes();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::uint64 sum_bytes_;
  ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoSubStreamMediaStatistic > sub_stream_stats_;
  ::google::protobuf::uint32 ssrc_;
  friend void  protobuf_AddDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_AssignDesc_pb_5fmedia_5fstatistic_2eproto();
  friend void protobuf_ShutdownFile_pb_5fmedia_5fstatistic_2eproto();

  void InitAsDefaultInstance();
  static ProtoMediaStatisticRep* default_instance_;
};
// ===================================================================


// ===================================================================

// ProtoMediaStatisticReq

// -------------------------------------------------------------------

// ProtoSubStreamMediaStatistic

// optional int32 sub_stream_index = 1;
inline bool ProtoSubStreamMediaStatistic::has_sub_stream_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_sub_stream_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_sub_stream_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoSubStreamMediaStatistic::clear_sub_stream_index() {
  sub_stream_index_ = 0;
  clear_has_sub_stream_index();
}
inline ::google::protobuf::int32 ProtoSubStreamMediaStatistic::sub_stream_index() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.sub_stream_index)
  return sub_stream_index_;
}
inline void ProtoSubStreamMediaStatistic::set_sub_stream_index(::google::protobuf::int32 value) {
  set_has_sub_stream_index();
  sub_stream_index_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.sub_stream_index)
}

// optional .stream_switch.ProtoSubStreamMediaType media_type = 2;
inline bool ProtoSubStreamMediaStatistic::has_media_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_media_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_media_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoSubStreamMediaStatistic::clear_media_type() {
  media_type_ = 0;
  clear_has_media_type();
}
inline ::stream_switch::ProtoSubStreamMediaType ProtoSubStreamMediaStatistic::media_type() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.media_type)
  return static_cast< ::stream_switch::ProtoSubStreamMediaType >(media_type_);
}
inline void ProtoSubStreamMediaStatistic::set_media_type(::stream_switch::ProtoSubStreamMediaType value) {
  assert(::stream_switch::ProtoSubStreamMediaType_IsValid(value));
  set_has_media_type();
  media_type_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.media_type)
}

// optional uint64 total_bytes = 20;
inline bool ProtoSubStreamMediaStatistic::has_total_bytes() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_total_bytes() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_total_bytes() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoSubStreamMediaStatistic::clear_total_bytes() {
  total_bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_total_bytes();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::total_bytes() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.total_bytes)
  return total_bytes_;
}
inline void ProtoSubStreamMediaStatistic::set_total_bytes(::google::protobuf::uint64 value) {
  set_has_total_bytes();
  total_bytes_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.total_bytes)
}

// optional uint64 key_bytes = 21;
inline bool ProtoSubStreamMediaStatistic::has_key_bytes() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_key_bytes() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_key_bytes() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoSubStreamMediaStatistic::clear_key_bytes() {
  key_bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_key_bytes();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::key_bytes() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.key_bytes)
  return key_bytes_;
}
inline void ProtoSubStreamMediaStatistic::set_key_bytes(::google::protobuf::uint64 value) {
  set_has_key_bytes();
  key_bytes_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.key_bytes)
}

// optional uint64 expected_frames = 30;
inline bool ProtoSubStreamMediaStatistic::has_expected_frames() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_expected_frames() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_expected_frames() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProtoSubStreamMediaStatistic::clear_expected_frames() {
  expected_frames_ = GOOGLE_ULONGLONG(0);
  clear_has_expected_frames();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::expected_frames() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.expected_frames)
  return expected_frames_;
}
inline void ProtoSubStreamMediaStatistic::set_expected_frames(::google::protobuf::uint64 value) {
  set_has_expected_frames();
  expected_frames_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.expected_frames)
}

// optional uint64 total_frames = 31;
inline bool ProtoSubStreamMediaStatistic::has_total_frames() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_total_frames() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_total_frames() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ProtoSubStreamMediaStatistic::clear_total_frames() {
  total_frames_ = GOOGLE_ULONGLONG(0);
  clear_has_total_frames();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::total_frames() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.total_frames)
  return total_frames_;
}
inline void ProtoSubStreamMediaStatistic::set_total_frames(::google::protobuf::uint64 value) {
  set_has_total_frames();
  total_frames_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.total_frames)
}

// optional uint64 key_frames = 32;
inline bool ProtoSubStreamMediaStatistic::has_key_frames() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_key_frames() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_key_frames() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ProtoSubStreamMediaStatistic::clear_key_frames() {
  key_frames_ = GOOGLE_ULONGLONG(0);
  clear_has_key_frames();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::key_frames() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.key_frames)
  return key_frames_;
}
inline void ProtoSubStreamMediaStatistic::set_key_frames(::google::protobuf::uint64 value) {
  set_has_key_frames();
  key_frames_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.key_frames)
}

// optional uint64 last_gov = 33;
inline bool ProtoSubStreamMediaStatistic::has_last_gov() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ProtoSubStreamMediaStatistic::set_has_last_gov() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ProtoSubStreamMediaStatistic::clear_has_last_gov() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ProtoSubStreamMediaStatistic::clear_last_gov() {
  last_gov_ = GOOGLE_ULONGLONG(0);
  clear_has_last_gov();
}
inline ::google::protobuf::uint64 ProtoSubStreamMediaStatistic::last_gov() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoSubStreamMediaStatistic.last_gov)
  return last_gov_;
}
inline void ProtoSubStreamMediaStatistic::set_last_gov(::google::protobuf::uint64 value) {
  set_has_last_gov();
  last_gov_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoSubStreamMediaStatistic.last_gov)
}

// -------------------------------------------------------------------

// ProtoMediaStatisticRep

// optional uint32 ssrc = 1;
inline bool ProtoMediaStatisticRep::has_ssrc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoMediaStatisticRep::set_has_ssrc() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoMediaStatisticRep::clear_has_ssrc() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoMediaStatisticRep::clear_ssrc() {
  ssrc_ = 0u;
  clear_has_ssrc();
}
inline ::google::protobuf::uint32 ProtoMediaStatisticRep::ssrc() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoMediaStatisticRep.ssrc)
  return ssrc_;
}
inline void ProtoMediaStatisticRep::set_ssrc(::google::protobuf::uint32 value) {
  set_has_ssrc();
  ssrc_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoMediaStatisticRep.ssrc)
}

// optional int64 timestamp = 2;
inline bool ProtoMediaStatisticRep::has_timestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoMediaStatisticRep::set_has_timestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoMediaStatisticRep::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoMediaStatisticRep::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 ProtoMediaStatisticRep::timestamp() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoMediaStatisticRep.timestamp)
  return timestamp_;
}
inline void ProtoMediaStatisticRep::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoMediaStatisticRep.timestamp)
}

// optional uint64 sum_bytes = 3;
inline bool ProtoMediaStatisticRep::has_sum_bytes() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoMediaStatisticRep::set_has_sum_bytes() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoMediaStatisticRep::clear_has_sum_bytes() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoMediaStatisticRep::clear_sum_bytes() {
  sum_bytes_ = GOOGLE_ULONGLONG(0);
  clear_has_sum_bytes();
}
inline ::google::protobuf::uint64 ProtoMediaStatisticRep::sum_bytes() const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoMediaStatisticRep.sum_bytes)
  return sum_bytes_;
}
inline void ProtoMediaStatisticRep::set_sum_bytes(::google::protobuf::uint64 value) {
  set_has_sum_bytes();
  sum_bytes_ = value;
  // @@protoc_insertion_point(field_set:stream_switch.ProtoMediaStatisticRep.sum_bytes)
}

// repeated .stream_switch.ProtoSubStreamMediaStatistic sub_stream_stats = 64;
inline int ProtoMediaStatisticRep::sub_stream_stats_size() const {
  return sub_stream_stats_.size();
}
inline void ProtoMediaStatisticRep::clear_sub_stream_stats() {
  sub_stream_stats_.Clear();
}
inline const ::stream_switch::ProtoSubStreamMediaStatistic& ProtoMediaStatisticRep::sub_stream_stats(int index) const {
  // @@protoc_insertion_point(field_get:stream_switch.ProtoMediaStatisticRep.sub_stream_stats)
  return sub_stream_stats_.Get(index);
}
inline ::stream_switch::ProtoSubStreamMediaStatistic* ProtoMediaStatisticRep::mutable_sub_stream_stats(int index) {
  // @@protoc_insertion_point(field_mutable:stream_switch.ProtoMediaStatisticRep.sub_stream_stats)
  return sub_stream_stats_.Mutable(index);
}
inline ::stream_switch::ProtoSubStreamMediaStatistic* ProtoMediaStatisticRep::add_sub_stream_stats() {
  // @@protoc_insertion_point(field_add:stream_switch.ProtoMediaStatisticRep.sub_stream_stats)
  return sub_stream_stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoSubStreamMediaStatistic >&
ProtoMediaStatisticRep::sub_stream_stats() const {
  // @@protoc_insertion_point(field_list:stream_switch.ProtoMediaStatisticRep.sub_stream_stats)
  return sub_stream_stats_;
}
inline ::google::protobuf::RepeatedPtrField< ::stream_switch::ProtoSubStreamMediaStatistic >*
ProtoMediaStatisticRep::mutable_sub_stream_stats() {
  // @@protoc_insertion_point(field_mutable_list:stream_switch.ProtoMediaStatisticRep.sub_stream_stats)
  return &sub_stream_stats_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace stream_switch

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5fmedia_5fstatistic_2eproto__INCLUDED
